default_platform(:ios)

platform :ios do
  desc "Build Integration App"
  lane :build_integration_app do |options|
    build_app(
      workspace: "StreamChatIntegration.xcworkspace",
      scheme: options[:scheme],
      skip_archive: true,
      skip_codesigning: true
    )
  end
end
