# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

workspace 'StreamChatIntegration-XC'

target 'StreamChatIntegration-XC-CocoaPods' do
  project 'StreamChatIntegration-XC-CocoaPods.xcodeproj'
  pod 'StreamChatUI-XCFramework', '4.60.0'
end
