name: Test Integration

on:
  pull_request:
    branches:
      - main

  # Can be manually triggered
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_INSTALL_CLEANUP=1: 1 # Disable cleanup for homebrew, we don't need it on CI

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: macos-13
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        integration: [spm, spm-xc, cocoapods, cocoapods-xc, carthage-xc]
        include:
          - integration: spm
            integration_type: OSS
            scheme: StreamChatIntegration-SPM
            lane: build_oss_integration_app
          - integration: spm-xc
            integration_type: BINARY
            scheme: StreamChatIntegration-XC-SPM
            lane: build_xc_integration_app
          - integration: cocoapods
            integration_type: OSS
            scheme: StreamChatIntegration-CocoaPods
            lane: build_oss_integration_app
          - integration: cocoapods-xc
            integration_type: BINARY
            scheme: StreamChatIntegration-XC-CocoaPods
            lane: build_xc_integration_app
          - integration: carthage-xc
            integration_type: BINARY
            scheme: StreamChatIntegration-XC-Carthage
            lane: build_xc_integration_app

    steps:
    - uses: actions/checkout@v3.1.0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Fetch SDKs via given dependency option
      if: startsWith(matrix.integration_type, 'spm') == false
      run: ./scripts/fetch_dependencies.sh ${{ matrix.integration }}

    - name: Build Integration App
      run: bundle exec fastlane ${{ matrix.lane }} scheme:${{ matrix.scheme }}
